### ISSUE TITLE
Secure mode: error message when opening conversation screen by clicking on push notification

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#121] opened 2020-09-29 08:58 UTC
Hello,

I have upgraded to SDK 2.0.2 and implemented secure mode. I notice an error message "There was a problem retrieving this message..." after I clicked on push notification to open conversation. 

Steps to reproduce:
1. Make sure the app identify user for secure mode
2. Open contact form and send a message
3. Reply sent message on Help Scout mail box
4. The app will get notification, clicking on notification when the app closed
5. Notice that an error message ""There was a problem retrieving this message..." displayed in conversation screen although the internet connection is OK.

Beacon SDK version: 2.0.2

**Actual outcome**
Beacon always show error message when retrieving message in conversation screen after clicking on push notification.

**Expected outcome**
Beacon should retrieve message in conversation screen without issue after clicking on push notification.

Here is the screenshot of error message:

![hs_conversation_error_msg](https://user-images.githubusercontent.com/45462932/94536054-7f46c500-026c-11eb-9785-3ff06f6f873b.png)

Could you please help to fix it?
Thanks,
Binh

**Comment by jotaemepereira** [comment] 2020-09-29 17:43
Hey @BinhTNT! Can you provide us with the way you are initializing and opening your Beacon? Are you passing the signature when opening Beacon like this `HSBeacon.open(settings, signature: "{YOUR_SIGNATURE}")`? Let me know and we will continue from there.

**Comment by BinhTNT** [comment] 2020-09-30 06:57
Hi @jotaemepereira I attached source code for Beacon implementation on iOS. I also confirm that the signature generated by our back-end works fine and it has been passed to HSBeacon.open(). The authentication mode in Help Scout was "secure" to make sure it was opened in secure mode.

Notice that our project is using React Native, so please ignore the part of code related to React Native. I hope it would be helpful. Thanks

[hs_secure_src.zip](https://github.com/helpscout/beacon-ios-sdk/files/5303606/hs_secure_src.zip)

**Comment by jotaemepereira** [comment] 2020-09-30 16:17
@BinhTNT I've checked your code and I think I found the issue, you need to change the implementation of `HelpScoutBeacon.m`. The method `handlePushNotification` should be something like this:

```objective-c
- (void)handlePushNotification:(nonnull NSDictionary *)userInfo
{
    BOOL isBeaconPushNotification = [HSBeacon isBeaconPushNotification:userInfo];
    if(isBeaconPushNotification)
    {
        [HSBeacon handlePushNotification:userInfo beaconSettings:[self settings] signature:@"SIGNATURE"];
    }
}
```

That should make it work, let me know if it works.

**Comment by BinhTNT** [comment] 2020-10-01 16:40
Hi @jotaemepereira Thanks for your suggestion. I tried it out but it the issue still happened. I also found the case which did not happen the issue as below:
1. Launch app and open Beacon
2. Open Previous conversation
3. Send a message
4. Reply to receive push notification from support agent
5. Click on notification, notice that the conversations are retrieved without error message

If at step 2, I don't open Previous conversation, the issue will happen. It means if the app was closed, it will have the same problem.

**Comment by jotaemepereira** [comment] 2020-10-01 19:23
Hey @BinhTNT, are you calling `HSBeacon.logout()` anywhere in your app? Another thing that could be happening is that you are logging the user out when you close the app, and when the push notification is pressed the user is logged out and it is not possible to retrieve the conversation.

**Comment by scottyab** [comment] 2020-10-14 09:18
Hey @BinhTNT  (sorry I seem to have mentioned you a bunch today).  I'm assuming this issue is resolved as there's been no response to @jotaemepereira's question in 13 days to confirm your user still has a valid session (i.e no calls `HSBeacon.logout()`).

There may still be cause for a bug to be logged on our side as the error message here too general for my liking if the error is related to auth error.

**Comment by BinhTNT** [comment] 2020-10-14 09:28
Hi @scottyab Sorry for delay. I checked it carefully and  confirm that I didn't call HSBeacon.logout() in this case, as well as when closing the app. I have a question, do I need to log in user again when initializing the app, because not like android, on ios, it will open the app (closed before) after user clicking on push notification?

**Comment by jotaemepereira** [comment] 2020-10-14 18:32
Hey @BinhTNT, thanks for responding to our questions, after some thorough testing I was able to reproduce what you are seeing. I've created this [internal ticket](https://helpscout.atlassian.net/browse/IOSSDK-397) to track this, and we will let you know when it gets fixed.

**Comment by jotaemepereira** [comment] 2020-10-15 16:06
@BinhTNT There is a workaround you can use to solve this while we work on it. In your `HelpScoutBeacon.m` implementation you will need to login the user before calling `[HSBeacon handlePushNotification:userInfo beaconSettings:[self settings] signature: @"SIGNATURE"];`

It will be something like this:
```objective-c
- (void)handlePushNotification:(nonnull NSDictionary *)userInfo
{
    BOOL isBeaconPushNotification = [HSBeacon isBeaconPushNotification:userInfo];
    if(isBeaconPushNotification)
    {
        self.user = [[HSBeaconUser alloc] init];
        self.user.email = self.formEmail;
        [HSBeacon login:self.user];
        [HSBeacon handlePushNotification:userInfo beaconSettings:[self settings]];
    }
}
```

**Comment by BinhTNT** [comment] 2020-10-27 03:41
Hi @jotaemepereira Sorry for delay response. I tried the workaround, but it doesn't work. Hope it will be fixed in new release. Thanks

**Comment by ScottPetit** [comment] 2020-10-28 02:13
Hey 👋 @BinhTNT,

I just noticed that the code snippet linked was slightly incorrect and wanted to see if you had brought it over directly into your project?  The correct implementation would be to call `login:` on HSBeacon prior to calling `handlePushNotification` but ensuring that the signature is included when calling `handlePushNotification`.  That would look something like this:

```objc
- (void)handlePushNotification:(nonnull NSDictionary *)userInfo
{
    BOOL isBeaconPushNotification = [HSBeacon isBeaconPushNotification:userInfo];
    if(isBeaconPushNotification)
    {
        HSBeaconUser *user = [[HSBeaconUser alloc] init];
        user.email = @"some@email.com";
        [HSBeacon login:user];
        [HSBeacon handlePushNotification:userInfo beaconSettings:[self settings] signature:@"THIS_USERS_SIGNATURE"];
    }
}
```

One other requirement would be that the `HSBeaconUser` that you're logging into `HSBeacon` has it's `email` set to a nonempty/nonnull value.

**Comment by jotaemepereira** [comment] 2020-11-09 17:47
Hey @BinhTNT, were you able to try what ScottPetit suggested? That should make it work, if not please feel free to re-open this issue. Thanks!

**Comment by BinhTNT** [comment] 2020-11-11 07:43
Hi @jotaemepereira I have followed @ScottPetit suggest but the issue still happened. I even did a hard code the user mail in handlePushNotification but it didn't work. So now I reopen it. Thanks

**Comment by jotaemepereira** [comment] 2020-11-11 15:00
Hey @BinhTNT sorry for all the back and forth, we did some testing on our side and we were not able to reproduce the issue. I'm going to ask you once more to send me your code, this time I will create a project from scratch to see if I can reproduce what you are seeing. Thanks for your patience.

**Comment by BinhTNT** [comment] 2020-11-16 07:51
Hi @jotaemepereira I attached my code. Hope it would be helpful. Thanks

[hs_beacon_src.zip](https://github.com/helpscout/beacon-ios-sdk/files/5544821/hs_beacon_src.zip)

**Comment by jotaemepereira** [comment] 2020-11-16 15:29
Hey @BinhTNT thanks for providing the code! I did some digging and I think where the issue could be, but before confirming I need you to send me the code where you call `(void)handlePushNotification:(nonnull NSDictionary *)userInfo;` from. I think it is from your `AppDelegate` class. Thanks!

**Comment by BinhTNT** [comment] 2020-11-16 15:32
Hi @jotaemepereira Here is my AppDelegate. Thanks

[AppDelegate.m.zip](https://github.com/helpscout/beacon-ios-sdk/files/5547276/AppDelegate.m.zip)

**Comment by jotaemepereira** [comment] 2020-11-16 16:17
@BinhTNT I think I found what could be causing your issue. On your `AppDelegate` you are calling `[[HelpScoutBeacon instance] handlePushNotification:userInfo];` without setting the signature or the user in the `HelpScoutBeacon` class.

In cases where the app gets killed, and the push notification is tapped the `HelpScoutBeacon` class will lose the information stored for the signature or the user, so when calling it will fail.

I think what you need to do to fix this issue is to call from your `AppDelegate`: 

```objective-c
[[HelpScoutBeacon] init:@"YOUR-BEACON-ID" title:@"YOUR-TITLE"]];
[[HelpScoutBeacon] identify:@"theuser@email.com"]];
[[HelpScoutBeacon] handlePushNotification:userInfo signature:@"THE USER SIGNATURE"]];
```

So first you need to re-initialize your Beacon, then you need to identify your customer, then you need to add an extra parameter to the `handlePushNotification` in the `HelpScoutBeacon` class to receive a signature and pass that into the `[HSBeacon handlePushNotification]`.

You could save that user information into some key/value storage method so you can retrieve it when the app gets restarted.

Let me know if this helps!

**Comment by adrianne-helpscout** [comment] 2020-11-20 03:18
👋 @BinhTNT We will close this issue, for now, please reopen if @jotaemepereira solution doesn't fix your problem.

**Closed by adrianne-helpscout** 2020-11-20 03:18 UTC
Labels: bug

**Comment by BinhTNT** [comment] 2020-12-09 10:42
@jotaemepereira Sorry for late come back. Thank you for your solution. It works but sometimes the issue still happens randomly. I cannot figure out how to recreate it. Do you have any idea for a possibility that it occurs? Thanks
