### ISSUE TITLE
Changing focus mode doesn't do anything

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#126] opened 2020-10-29 20:49 UTC
Beacon version: 2.1.0

Steps to reproduce:
1: Set focus mode to ask first in the web UI
2:Open the beacon.

Expected:
The beacon should be opened in ask first mode.
Actual: 
The docs screen is shown without a navigation bar and it is impossible to reach the contact options.

![IMG_0580](https://user-images.githubusercontent.com/6479433/97630306-b0fba900-1a2f-11eb-829a-1871d305b031.PNG)

**Comment by sipersso** [comment] 2020-10-29 20:56
This issue can be reproduced in your sample app as well.

**Comment by ScottPetit** [comment] 2020-10-29 21:13
Hey @sipersso, 

I'm seeing the same thing with your Beacon.  I'm in the process of trying to figure out what's going as we haven't seen that with any of our other test Beacons.  I'll get back to you when I have more info and an internal issue we'll use for tracking it.

**Comment by sipersso** [comment] 2020-10-29 21:42
That's weird.. thanks for looking into it so quickly.

**Comment by ScottPetit** [comment] 2020-10-30 02:56
Hey @sipersso,

So I think this is basically a dupe of #125 but want to double check if you tried changing the `focusMode` to `askFirst` and were still seeing the same thing?  The reason I think this is a dupe of #125 is because the main difference between the `neutral` and `selfService` focus modes are in the navigation bar, which unfortunately are being hidden.  Here are two screenshots showing how your Beacon would look with a `selfService` and a `neutral` focus mode if the navigation bar wasn't hidden:

| Self Service | Neutral |
| ------ | ----- |
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-29 at 21 46 39](https://user-images.githubusercontent.com/2100009/97654589-3895e780-1a31-11eb-8054-b45ce74ddee9.png)| ![Simulator Screen Shot - iPhone 11 Pro - 2020-10-29 at 21 46 31](https://user-images.githubusercontent.com/2100009/97654595-39c71480-1a31-11eb-8cdc-95a377ef8a5a.png)

As you can see without the navigation bar they don't look any different.

All that said if you're still seeing the original screenshot you linked after setting the `focusMode` to `askFirst` then that would definitely be a problem and something we'd want to take a look at.

**Comment by sipersso** [comment] 2020-10-30 07:14
Hi Scott!

Ask first doesn't make any difference I am afraid :( On first install I can see the contact screen flashing for a split second and then the docs are shown... see the attached video [beacon.mov.zip](https://github.com/helpscout/beacon-ios-sdk/files/5463489/beacon.mov.zip)

**Comment by ScottPetit** [comment] 2020-11-09 18:49
Hey @sipersso,

I wanted to update you on this now that 2.1.1 is available.  So there's a bit of caching that happens with Beacon configs (5 minutes) so if you launch Beacon from a fresh app launch after that 5 minutes has passed then the Beacon should be configured with the appropriate `focusMode`.  Also there's a `focusModeOverride` property on `HSBeaconSettings` to allow you to customize the `focusMode` only on the client.

Let us know if you see any other issues with the `focusMode`.

**Closed by ScottPetit** 2020-11-09 18:49 UTC
Labels: bug
