### ISSUE TITLE
Error message displayed when sending message in secure mode

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#111] opened 2020-09-14 03:51 UTC
Hello,
I have upgraded Beacon SDK to version 2.0.1. I found an issue with secure mode, when I send a message in secure mode, I notice that there was a error message "Please use a valid email address" displayed and the message can't be sent at this time, but when I tap on "send message" button again, the message will be sent.

Could you please help to fix it?

Beacon SDK version: 2.0.1

**Actual outcome**
 An error “Please use a valid email address“ message displayed when sending a message in secure mode.

**Expected outcome**
The error message should not be displayed.

Here is the video link for the issue: https://drive.google.com/file/d/1Y3hbdW55clV_Ct4Wd9vTSg1qaY9Q-XSU/view?usp=sharing

Thanks,
Binh

**Comment by ScottPetit** [comment] 2020-09-14 14:18
Hey @BinhTNT , thanks for submitting it. We're currently QAing a fix for this with #94 so I'm going to include the [internal ticket](https://helpscout.atlassian.net/browse/IOSSDK-325) we have for that one, and let you know when the fix is out.

**Comment by adrianne-helpscout** [comment] 2020-09-15 18:58
Closing as this is a duplicate of #94

**Closed by adrianne-helpscout** 2020-09-15 18:58 UTC
Labels: bug
