### ISSUE TITLE
Unknown Attachment with ID

### ISSUE THREAD

**Issue by lewis-smith** [helpscout/beacon-ios-sdk#48] opened 2019-12-16 10:14 UTC
* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
Did not always allow messages to be submitted

And from the logs:

`Reply send error: Unknown Attachment with ID: 94fec05d-a3db-4044-a391-d7e4484db40a`

**Expected outcome**
Beacon should submit the message

**Screenshots or GIFs**
![IMG_9C9E74BB3E2E-1](https://user-images.githubusercontent.com/1905433/70898468-a0e00400-1fec-11ea-95dc-72e2e79a1edc.jpeg)

**Comment by codenameDuchess** [comment] 2019-12-17 00:09
Hi @lewis-smith thank you for reporting this issue and sorry for the trouble. We'll investigate and report back.

**Comment by codenameDuchess** [comment] 2019-12-17 00:09
Internal Jira Reference https://helpscout.atlassian.net/browse/IOSSDK-56

**Comment by lewis-smith** [comment] 2019-12-27 14:50
this is definitely not an isolated incident. I'll add more screenshots as I get them.

as it stands I don't have a fallback mechanism to get logs when helpscout doesn't work so it's difficult to provide more information from 'the field'.

https://www.dropbox.com/s/72q9pbga72pe6w8/image0.png?dl=0

**Comment by lewis-smith** [comment] 2019-12-27 15:35
https://www.dropbox.com/s/7mpkoz4bhvh5bh4/image1.png?dl=0

**Comment by lewis-smith** [comment] 2019-12-27 15:37
I noticed that on my device it wouldn't allow me to submit the form, but after deleting the attachments it did work. I don't have the exact size of the attachments but they were in kb not mb, so shouldn't have been too big.

Not sure if this is relevant or related just trying to feedback as much as I can to get this fixed.

**Comment by codenameDuchess** [comment] 2020-01-15 21:25
Thanks for providing these additional details @lewis-smith 👍 I've included them in our Jira ticket so we can be sure we resolve the issue.

**Comment by lewis-smith** [comment] 2020-01-30 21:22
Any news on this one?

**Comment by shaunmcilroy** [comment] 2020-01-31 10:19
Hi @lewis-smith - we don't have an update for you at this time but we'll definitely keep you in the loop with any updates from the team.

**Comment by ScottPetit** [comment] 2020-02-25 18:15
Hey @lewis-smith so I've got a couple of pieces of news to share.  

As far as the first issue you wrote in about (the `Unknown Attachment with ID` error) I, unfortunately, don't have any news about a solution for that one.  I've been digging into how we're handling uploading attachments and haven't found anything in the SDK to reproduce it.  Because of this, and the lack of other reports about unknown attachments IDs, we don't really have a clear path for fixing this one at this time.

As far as the other issues you noted, I have some good news on those.  So although they appear to be related to the `Unknown Attachment with ID` error they were actually a client-side issue related to how we were doing form validation with prefilled forms.   This issue was resolved with [Version 1.0.3](https://github.com/helpscout/beacon-ios-sdk/releases/tag/1.0.3) that came out early January.  If you’re still seeing errors composing messages after updating to 1.0.3 please let us know.

**Closed** 2020-03-03 20:34 UTC
Labels: bug
