### ISSUE TITLE
Beacon prevents app submission with bitcode enabled

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#124] opened 2020-10-29 16:22 UTC
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon install method: [ ] Carthage, [ ] CocoaPods, [x] Manual

**Actual outcome**
Beacon did not allow to submit an app build to App Store with bitcode enabled.
Turning off bitcode for the whole app target resolved the issue.

**Expected outcome**
Beacon should support bitcode generation.

**Screenshots or GIFs**
```
bitcode bundle could not be generated because '/Users/xxx/Library/Developer/Xcode/DerivedData/App-aojzbxatndzmtsgkygqkesplocua/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/Beacon.framework/Beacon' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/xxx/Library/Developer/Xcode/DerivedData/App-aojzbxatndzmtsgkygqkesplocua/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/Beacon.framework/Beacon' for architecture arm64
```

**Comment by andreyz** [comment] 2020-10-29 16:26
@ScottPetit This seems like a novel issue introduced after conversion to xcframework. Maybe simplify forgot to flip the enable bitcode switch?

**Comment by ScottPetit** [comment] 2020-10-29 19:39
Hey @andreyz,

Thanks for the report.  You're right this was an unintentional side effect of the `xcframework` introduction.  We're tracking it internally [here](https://helpscout.atlassian.net/browse/IOSSDK-409) and will let you know when we have a fix.

**Comment by lewis-smith** [comment] 2020-11-09 17:34
This is back again with 2.1 the second.

**Comment by lewis-smith** [comment] 2020-11-09 17:37
Possibly just unlucky timing on my part. I see that there is a 2.1.1, but `pod update` is fetching 2.1.0 which was previously "removed from sale". Hopefully the CDN will catch up soon.

**Comment by ScottPetit** [comment] 2020-11-09 18:44
Hey @andreyz & @lewis-smith,

This should be resolved with the latest version (2.1.1).  Check out the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md) for everything else that's changed.

@lewis-smith I just verified this in a test project with a manual installation and it worked just fine.  Feel free to open up a new issue if you have any trouble integrating it via Cocoapods (also the CDN has caught up).

**Comment by lewis-smith** [comment] 2020-11-10 15:30
With 2.1.1 it uploads fine, but then fails the checks that are done post upload. I do not see these issues with 2.0.2

ITMS-90562: Invalid Bundle - The app submission can not be successfully recompiled from bitcode due to missing symbols during linking. You can try to reproduce and diagnose such issues locally by following the instructions from: https://developer.apple.com/library/archive/technotes/tn2432/_index.html

ITMS-90562: Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

**Comment by ScottPetit** [comment] 2020-11-10 15:35
@lewis-smith so the app successfully archives and then fails on upload to App Store Connect, right?  And yea this seems to be a byproduct of the migration to XCFramework which happened with 2.1.1 whereas 2.0.2 used .frameworks instead.

**Comment by lewis-smith** [comment] 2020-11-10 15:50
It archives and uploads, but then fails the checks Apple do after upload.

**Comment by parrots** [comment] 2020-11-12 18:36
Easy way to reproduce this issue: if you export an app that includes 2.1.x after archiving it, for Ad Hoc distribution, you can see the error after it does the compiling bitcode step.

```
ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -L /var/folders/2h/bxf5jf4s2xn9vfxk_83xjwth0000gn/T/ipatool20201112-36332-6v8j2u/thinned-out/arm64/Payload/Slopes.app/Frameworks --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.1.sdk -o /var/folders/2h/bxf5jf4s2xn9vfxk_83xjwth0000gn/T/ipatool20201112-36332-6v8j2u/thinned-out/arm64/Payload/Slopes.app/Frameworks/Beacon.framework/Beacon --generate-dsym /var/folders/2h/bxf5jf4s2xn9vfxk_83xjwth0000gn/T/ipatool20201112-36332-6v8j2u/thinned-out/arm64/Payload/Slopes.app/Frameworks/Beacon.framework/Beacon.dSYM --strip-swift-symbols /var/folders/2h/bxf5jf4s2xn9vfxk_83xjwth0000gn/T/ipatool20201112-36332-6v8j2u/thinned-in/arm64/Payload/Slopes.app/Frameworks/Beacon.framework/Beacon
Status: pid 40767 exit 1
Stdout:
    SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
```

**Comment by gm-maddcog** [comment] 2020-11-12 22:38
Yes I am facing the same issue too and it can be track down to the Beacon framework using the troubleshooting from Apple otool -l -arch all <PathToArchive>/Products/Applications/<AppName>.app/<AppBinary> | grep __llvm_prf
https://developer.apple.com/library/archive/qa/qa1964/_index.html#//apple_ref/doc/uid/DTS40017675-CH1-INSPECT

**Comment by scottyab** [comment] 2020-11-13 13:50
Hey @lewis-smith @gm-maddcog @andreyz @parrots Just to confirm we are aware of the issue and tracking it internally [here](https://helpscout.atlassian.net/browse/IOSSDK-409). We'll keep you updated via this issue. Thanks for the feedback and reproduction information.

**Comment by andreyz** [comment] 2020-11-15 16:49
@ScottPetit this might be helpful https://pspdfkit.com/blog/2020/supporting-xcframeworks/

**Comment by ScottPetit** [comment] 2020-11-19 22:17
👋 @andreyz, @lewis-smith, @xaphod, @parrots , @gm-maddcog,

Just wanted to let y'all know that you should now be able to distribute your apps with Bitcode enabled with the latest version (2.1.2) of Beacon.  You can read more about the updates in the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md), but perhaps the most relevant info would be we also added support for Swift Package Manager as well.  Thanks for all the info and docs, somehow this issue has more information about Bitcode and XCFrameworks than Apples docs.

**Closed by ScottPetit** 2020-11-19 22:17 UTC
Labels: bug
