### ISSUE TITLE
Prefill not called when opening contact form the second time

### ISSUE THREAD

**Issue by florianbuerger** [helpscout/beacon-ios-sdk#34] opened 2019-08-21 13:36 UTC
1) Open the contact from, fill in body & attachments `-[HSBeaconDelegate prefill:]` is called as expected
2) Dismiss the form without sending the message
3) Open the message form again

Now `-[HSBeaconDelegate prefill:]` is not called. Doesn't matter if `-[HSBeacon reset]` is called in between. 

I was expecting that `prefill` is called every time before the form is presented. Is this a bug or intentional?

**Comment by adrianne-helpscout** [comment] 2019-10-30 19:06
https://helpscout.atlassian.net/browse/IOSSDK-8

**Comment by ScottPetit** [comment] 2019-11-14 21:56
Hey @florianbuerger,

Thanks for bringing this to our attention.  I wanted to let you know that we've made some improvements to how this handled with the latest version of the SDK 1.0.2.  

The newest implementation, won't call `prefill` every time, but will be sure to call it if you call `[HSBeacon reset]`.  The reason we aren't guaranteeing `prefill` every time is for us it doesn't seem correct to call `prefill` when a user already has a draft message in progress.  In that case it's not clear which data should take precedence so we just default to leaving their draft message intact.  However when calling `[HSBeacon reset]` draft messages are cleared and you would therefore receive a `prefill` call on your next presentation of Beacon.

Let us know if you run into any issues, and thanks for the detailed bug report.

**Comment by ispiropoulos** [comment] 2021-01-22 09:00
Hi @ScottPetit 

We are implementing Beacon with secure mode. There is a particular beacon opening in secure mode after the user completes a particular flow and then press a button.

Now, the first time this flow occurs and the user presses the button, the `HSBeaconDelegate.prefill` is called. Other times, it does not.

Notes:
- A new BeaconSettings object is created every time the user presses a button
- The delegate of that BeaconSettings object is a new instance every time

Things we have tried:
- We have tried HSBeacon.reset before initialising the BeaconSettings objects
- We have tried HSBeacon.reset on the HSBeaconDelegate.onBeaconClose method

Beacon SDK Version: 2.1.2

A possible workaround would be creating a single BeaconSettings instance to cover all occurrences of that particular flow, but we would like to know whether you see something wrong in the current implementation explained above or if this is an issue on the Beacon SDK side, since I read above that `HSBeacon.reset` should make the delegate call prefill the next time the beacon is opened.

**Comment by hs-gv** [comment] 2021-01-25 17:01
Hello @ispiropoulos .  We've attempted to duplicate the issue you are seeing on v2.2.0, but we are unable reproduce.  We would like to get some more information to try and figure this out.  Could you try these two things?

1. What happens if you remove the call to `reset` and then reopen the Beacon a second time? Are the user drafts preserved?  

2. If you keep your `reset` call, when you open the Beacon the 2nd time, is the form empty?

Looking forward to hearing from you.

**Comment by ispiropoulos** [comment] 2021-01-26 08:15
Hi @hs-gv 

It all depends on wether I instantiate a new `HSBeaconSettings` object the second time I open the beacon.

Whatever I do, (either call `reset` or not) the second time I initiate a `HSBeaconSettings` object, set its `delegate` and open it with `HSBeacon`, `prefill` is not getting called and the form is empty (no subject or body - these are what I want to be profiled with specific (new) values each time the beacon opens)

If it is of any help, the the beacon id for the time being is always the same.

**Comment by hs-gv** [comment] 2021-01-26 22:50
Thanks for the additional information @ispiropoulos .  I'll consult with the team and get back to you.

**Comment by ispiropoulos** [comment] 2021-01-27 06:59
Thank you @hs-gv

**Comment by codenameDuchess** [comment] 2021-01-27 23:53
Hi @ispiropoulos,

Unfortunately, we've still been unable to recreate this issue (using Beacon version 2.1.2 or version 2.2.0). Made sure to instantiate a new settings object each time (with the same Beacon ID), and set its delegate, then open the Beacon. Tried both the `HSBeacon.navigate` to Ask Message route and `HSBeacon.open` and then navigating to the message page manually. Each time we see the form pre-filled and the delegate function called once each time the Ask Message screen is presented. 

Is there any chance that you are not keeping a strong reference to your delegate when you set it the second time around? The only thing we can figure is it might be getting deallocated before we call the `HSBeaconDelegate.prefill` function.

**Comment by ispiropoulos** [comment] 2021-01-28 07:26
> Hi @ispiropoulos,
> 
> Unfortunately, we've still been unable to recreate this issue (using Beacon version 2.1.2 or version 2.2.0). Made sure to instantiate a new settings object each time (with the same Beacon ID), and set its delegate, then open the Beacon. Tried both the `HSBeacon.navigate` to Ask Message route and `HSBeacon.open` and then navigating to the message entry view controller manually. Each time we see the form pre-filled (via the delegate function being called once each time the Ask Message screen is presented).
> 
> Is there any chance that you are not keeping a strong reference to your delegate when you set it the second time around? The only thing we can figure is it might be getting deallocated before we call the `HSBeaconDelegate.prefill` function.

Hi @codenameDuchess and thank you for the effort you put.

The user flow is exactly the same as in the first time and the delegate is indeed kept by strong reference. As a matter of fact `onBeaconClose` is getting called every single time.

P.S. On my [initial comment about this issue](https://github.com/helpscout/beacon-ios-sdk/issues/34#issuecomment-765249035) I stated that we are using secure mode, I am just let you know of this again just in case it helps with your tests.

Thank you again.

**Comment by codenameDuchess** [comment] 2021-01-28 23:53
Hi @ispiropoulos,

Thank you for your patience as we tracked this down, and my apologies for missing your earlier comment that you were in secure mode. I was able to reproduce this issue (in both version 2.1.2 and 2.2.0). Sorry for the trouble.  

I've opened an [internal ticket](https://helpscout.atlassian.net/browse/IOSSDK-472) so that we can resolve this bug and we'll let you know as soon as its available in a release.

**Comment by ispiropoulos** [comment] 2021-01-29 06:42
> Hi @ispiropoulos,
> 
> Thank you for your patience as we tracked this down, and my apologies for missing your earlier comment that you were in secure mode. I was able to reproduce this issue (in both version 2.1.2 and 2.2.0). Sorry for the trouble.
> 
> I've opened an [internal ticket](https://helpscout.atlassian.net/browse/IOSSDK-472) so that we can resolve this bug and we'll let you know as soon as the fix is available in a release.

Thank you @codenameDuchess

**Comment by ScottPetit** [comment] 2021-04-22 16:17
@ispiropoulos Just wanted to let you know that this is fixed with the latest release (2.2.1).  Thanks for bringing it to our attention.

**Closed by ScottPetit** 2021-04-22 16:17 UTC
Labels: bug

**Comment by ispiropoulos** [comment] 2021-04-23 09:23
> @ispiropoulos Just wanted to let you know that this is fixed with the latest release (2.2.1). Thanks for bringing it to our attention.

You are welcome @ScottPetit thank you for the fast response and the resolution. Will be updating our app soon and removing our workaround as well.
