### ISSUE TITLE
With setUseNavigationBarAppearance not enabled close button can be hidden

### ISSUE THREAD

**Issue by ay8s** [helpscout/beacon-ios-sdk#9] opened 2018-10-26 23:31 UTC
If we set the color to the same color as we use for buttons throughout the app the close button can be hidden.

Might need some additional configuration options as if I set the color to our default themes navigation color which is white, the title is then not visible, even if I enable setUseNavigationBarAppearance

**Comment by ay8s** [comment] 2018-10-26 23:53
Looks like previous versions of Beacon didn't change the close button color based on the apps UIAppearance.

**Comment by jgritman** [comment] 2018-10-27 00:02
Hi Andrew! Thanks for bringing this to our attention! 

Could you send us the specific color configuration you have (`UIAppearance` and `HSBeaconSettings`) so we can make sure we're testing this correctly?

**Comment by ay8s** [comment] 2018-10-27 00:09
So looks like its related to us adding the following in order to tint alerts etc...

```
[[UIView appearance] setTintColor:[UIColor colorFromHexString:@"#2C4BFF"]];
```

This color matches the one we have defined within HelpScout on web. For now I'm removing the line above so we can get a release out.

**Comment by jgritman** [comment] 2018-10-27 00:19
My coworker @samsymons  knows more about our color handling so I'll let him chime in here next week and see if there's anything we could do on our end. 

For your case, would something like this work?
```
    [[UIView appearanceWhenContainedInInstancesOfClasses:[UIAlertController class]] setTintColor:[UIColor colorFromHexString:@"#2C4BFF"]];
```

**Comment by ay8s** [comment] 2018-10-27 01:40
Will look at next week. Not a huge deal 👍  

We already set attributes on navigation bar titles etc but they don't get carried across when setUseNavigationBarAppearance is enabled. Simplest solution may be to add a UINavigationController subclass HSNavigationController and allow us to control it that way also.

**Comment by samsymons** [comment] 2018-10-30 23:05
@ay8s Thanks for reporting this! I added a tint color override to `UIView` in our Beacon test app and reproduced this issue, great catch; I'm working on a fix for this now, with the hope of getting it released in the next couple of days. Thanks again!

**Comment by ay8s** [comment] 2018-10-30 23:20
@samsymons All good, I adjusted out UIAlertController tinting to @jgritman's suggestion. Will keep an eye out for anything else 👍 

Does Beacon handle cases if the color defined is white or super light and adjust the title/buttons accordingly?

**Comment by samsymons** [comment] 2018-11-05 18:43
@ay8s Yep, Beacon has color detection to make sure that the title and bar button items are always visible. We use the same method of color detection as Beacon on the web, so it should be consistent.

We're also just wrapping up fixes for the `UIView` appearance issue and hope to have a release out for you this week!

**Comment by samsymons** [comment] 2019-02-08 04:03
We tested out a couple fixes for this internally, but ended up playing whack-a-mole with new issues caused by the changes here; for now I'm gonna close this out, as there's a workaround, but we'll keep an eye on any other tint color related issues popping up.

**Closed by samsymons** 2019-02-08 04:03 UTC
