### ISSUE TITLE
User attributes cannot be sent if user changes pre-filled email into another email that has never sent a message

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#123] opened 2020-10-13 14:58 UTC
Hello,

Currently I have a problem with user attributes. When I attempt to send a message, I tried to change the pre-filled email into another email which has never sent message to Help Scout, then I sent a message. I noticed that the user attributes are not displayed on Help Scout side bar.

Steps to reproduce:
1. Make sure user attributes works well
2. Open Beacon contact form in basic mode with pre-filled email (A)
3. Change pre-filled email into another email (B) that has never sent e message
4. Send a message with modified email (B)
5. Notice that user attributes are not displayed on Help Scout in side bar

**Actual outcome**
User attributes are not displayed on Help Scout side bar

**Expected outcome**
User attributes should be displayed on Help Scout side bar together the modified email

Note that, If I open contact form again, the email will be pre-filled with email B, at this time if I send a message, the issue will not happen.

Beacon SDK version: 2.0.2

Could you please help to check the issue?
Thanks,
Binh

<img width="278" alt="Screen Shot 2020-10-13 at 9 49 41 PM" src="https://user-images.githubusercontent.com/45462932/95877206-1009be80-0d9e-11eb-8fe3-087fe1eb1830.png">

**Comment by scottyab** [comment] 2020-10-14 09:00
Hey @BinhTNT There has been some releated fixes in this area with the next version 2.1.0. We're currently in test phase and it seems to be fixed as I cannot recreate this issue. I see the user attributes for the new customer (via the newly input email B) in the side bar and inspecting the API traffic it looks as I expect. 
![Image 2020-10-14 at 9 56 42 am](https://user-images.githubusercontent.com/404105/95966984-a7552d00-0e03-11eb-8bf3-a0698b0d73ef.png)

Once 2.1.0 is released we should circle back and hopefully you'll find this issue resolved. Thanks for reporting it with such clear steps to reproduce and detail. 👍

**Comment by scottyab** [comment] 2020-10-14 09:20
Internal issue tracking https://helpscout.atlassian.net/browse/IOSSDK-376 (fixed in 2.1)

**Comment by ScottPetit** [comment] 2020-10-29 15:52
👋 Hey @BinhTNT,

Thanks for filing this. Just wanted to let you know that this should be resolved in the latest release (2.1.0). If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Comment by ScottPetit** [comment] 2020-10-30 19:21
Hi @BinhTNT We discovered an issue with version 2.1.0 where under certain configurations Beacon wouldn't be able to be dismissed. Therefore we decided to remove 2.1.0 and aim to resolve this issue in the next release. We'll update you once this is released, thank you for your patience.

**Comment by ScottPetit** [comment] 2020-11-09 18:38
👋 Hey @BinhTNT,

Thanks for filing this. Just wanted to let you know that this should be resolved in the latest release (2.1.1). If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Closed by ScottPetit** 2020-11-09 18:38 UTC
Labels: bug
